reflect.go
I needed some extra fields to manually generate schemas, so I've added them.
Struct tags should be added for them in general, but right now I don't need it to work via reflect so I just added what I needed.
=> added needed fields to jsonshcema

reflect.go, reflect_test.go
Do we need to process unmarked fields in structs? Most probably not :) This PR fixes the issue
=> Added logic to ignore unmarked fields when generating list of properties

reflect.go, reflect_test.go
The problem was: the package processes anonymous and non-exported fields of structures incorrectly. That is, non-exported fields were are visible in the output (they should not) and anonymous fields are treated like normal ones and included as separate types into the schema. Base type must extend with anonymous fields, not receive a reference to new type. I'm talking about following situation:
```
type A struct {
FieldA int
}
type B struct {
A
FieldB int
}
```
Currently json schema will contain both types A and B and type B will have 2 properties: `FieldB` (integer) and `A` (reference to type `A`), but there should be only 1 type `B` with 2 properties: `FieldA` and `FieldB`.
=> Unexported and anonymous fields support

README.md, reflect.go
According to https://spacetelescope.github.io/understanding-json-schema/reference/schema.html and http://json-schema.org/latest/json-schema-core.html#rfc.section.6.1, "The root schema of a JSON Schema document SHOULD use this keyword."
=> Add `$schema` keyword support

reflect.go, reflect_test.go
Since Go encodes them as base64 per https://golang.org/pkg/encoding/json/#Marshal
i.e. Have type 'string' and contain a 'media' property per http://json-schema.org/latest/json-schema-hypermedia.html#rfc.section.4.3
=> Expect byte slices to be encoded as base64

reflect.go, reflect_test.go
Hello again! This one is a little more controversial. I have two goals:
* I'd like to generate JSON schemas from structs generated from protobuf messages. I'm specifically using gogoproto, but I'd like to do this in a way that is also compatible with upstream protobuf.
* I'd like to generate JSON schemas that allow extraneous keys in objects, with the understanding that JSON objects would pass JSON schema validation but then have their extraneous keys dropped upon unmarshal to struct.
I'm not entirely convinced that the protobuf parts belong in this repo (as opposed to a fork), and I'm open to implementing this a different way. I'd like to add some tests for the `Reflector`/`additionalProperties` change, but I won't get to that until tomorrow.
=> Support protobuf flavoured JSON

fixtures/allow_additional_props.json, fixtures/defaults.json, fixtures/required_from_jsontags.json, reflect.go, reflect_test.go
As opposed to inferring that fields that are tagged `json:",omitempty"` are not required. This allows schemas (which I see as primarily useful when unmarshaling JSON) to be decoupled from how structs are marshaled.
This PR also includes a commit that updates the tests to ensure the `Reflector` options do the right thing when set.
=> Optionally specify required struct fields using a jsonschema tag

README.md, fixtures/defaults_expanded_toplevel.json, reflect.go, reflect_test.go
The current implementation makes the top level struct to go inside the definition & referenced, this is perfectly fine, However in most ideal situations, the top level schema is expanded like the following example 
```json
{
"id": "http://some.site.somewhere/entry-schema#",
"$schema": "http://json-schema.org/draft-04/schema#",
"description": "schema for an fstab entry",
"type": "object",
"required": [ "storage" ],
"properties": {
"storage": {
"type": "object",
"oneOf": [
{ "$ref": "#/definitions/diskDevice" },
{ "$ref": "#/definitions/diskUUID" },
{ "$ref": "#/definitions/nfs" },
{ "$ref": "#/definitions/tmpfs" }
]
},
"fstype": {
"enum": [ "ext3", "ext4", "btrfs" ]
},
"options": {
"type": "array",
"minItems": 1,
"items": { "type": "string" },
"uniqueItems": true
},
"readonly": { "type": …
```
=> Expanded toplevel struct

fixtures/allow_additional_props.json, fixtures/defaults.json, fixtures/defaults_expanded_toplevel.json, fixtures/required_from_jsontags.json, reflect.go, reflect_test.go
This PR allows the definition of structs like:
```go
type Foo struct {
Bar string `json:"bar" jsonschema:"pattern=abc"`
}
```
Which will generate schemas like:
```
"bar": {
"pattern": "abc",
"type": "string"
}
```
=> Add support for pattern tag

README.md, fixtures/allow_additional_props.json, fixtures/defaults.json, fixtures/defaults_expanded_toplevel.json, fixtures/required_from_jsontags.json, reflect.go, reflect_test.go
Hi there and thanks for a very useful library.
This patch adds some basic support for the generic keywords `title`, `description`, `examples`, `default`.
Let me know if this would be interesting to others,
Thanks!
=> Generic keywords support: title, description, examples, default

README.md
As per source code a colon will be used get/split tags and '=' will be used in internal split of tags under 'jsonschema' tag. Fixed the example
=> Fixed Example

README.md, fixtures/oneof.json, reflect.go, reflect_test.go
This PR allows you to use oneof for the 2 following use-cases:
- Make fields required by group using the tag `jsonschema:"oneof_required=group1"`. Useful to say that an object required some fields OR some others filed
Result:
`
"oneOf": [
{
"required": [
"child1",
"child4"
],
"title": "group1"
},
{
"required": [
"child2"
],
"title": "group2"
}
]
`
- have field with 2 types using tag `jsonschema:"oneof_type=string,array"`
Result: `"oneOf": [
{
"type": "string"
},
{
"type": "array"
}
]`
=> feat: add oneof ( required and type ) tag

fixtures/allow_additional_props.json, fixtures/defaults.json, fixtures/defaults_expanded_toplevel.json, fixtures/ignore_type.json, fixtures/required_from_jsontags.json, go.mod, go.sum, reflect.go
Change `Type.Properties` from `map[string]*Type` to `*orderedmap.OrderedMap` to preserve sequence of struct fields in rendered JSON.
The bulk of the changed code are actually the tests, getting them passing again :)
Closes #50
=> Ordered properties

README.md, fixtures/allow_additional_props.json, fixtures/defaults.json, fixtures/defaults_expanded_toplevel.json, fixtures/ignore_type.json, fixtures/required_from_jsontags.json, reflect.go, reflect_test.go
As per #52 this PR adds support for extra fields on generated schema types, with the struct tag `jsonschema_extras`.  It also includes a test of this functionality.  Sample:
```go
type Apple struct { 
Banana string `jsonschema_extras:"widget=mango"`
}
jsonschema.Reflect(Apple{})
```
```json
{
"properties": {
"Banana": {
"type": "string",
"widget": "mango"
}
}
}
```
=> Extra Fields on Generated Types

fixtures/allow_additional_props.json, fixtures/defaults.json, fixtures/ignore_type.json, reflect.go, reflect_test.go
Fixes #56 
This went undetected because the tabular test behavior was to unmarshal JSON into a Schema and then re-marshal it.  To catch this in the future, I'm adding a test that marshals a Schema and compares it directly with the fixture.
First commit is just to add the failing test and show that it fails via CI.  Next commit will fix the issue.
=> Fix Schema Marshaling

fixtures/fully_qualified.json, fixtures/no_ref_qual_types.json, fixtures/no_reference.json, reflect.go, reflect_test.go
This PR adds two options to the Reflector.  I'll quote from the source:
```go
// Do not reference definitions.
// All types are still registered under the "definitions" top-level object,
// but instead of $ref fields in containing types, the entire definition
// of the contained type is inserted.
// This will cause the entire structure of types to be output in one tree.
DoNotReference bool
// Use package paths as well as type names, to avoid conflicts.
// Without this setting, if two packages contain a type with the same name,
// and both are present in a schema, they will conflict and overwrite in
// the definition map and produce bad output.  This is particularly
// noticeable when using DoNotReference.
FullyQualifyTypeNames bool
```
My particular use case was taking the output and …
=> Add DoNotReference and FullyQualifyTypeNames

fixtures/disable_inlining_embedded.json, reflect.go, reflect_test.go
https://github.com/ghodss/yaml treats embedded structs differently to the `json` package. In particular, this struct:
```
type Outer struct {
Inner
}
type Inner struct {
Foo string `yaml:"foo"`
}
var myStruct = &Outer{Foo: "bar}
```
Will be ser/de to/from this yaml:
```
inner:
foo: bar
```
This PR adds an option to support generating JSON schemas that can be used from the `gopkg.in/yaml` package
=> Add YAMLEmbeddedStructs option

fixtures/nullable.json, reflect.go, reflect_test.go
This PR adds the `nullable` tag to create a `oneOf` with the auto-generated type plus the `null` type.
=> Add nullable tag

fixtures/yaml_inline.json, fixtures/yaml_inline_embed.json, reflect.go, reflect_test.go
One caveat with this PR is that I wasn't entirely sure of the desired interaction here with https://github.com/alecthomas/jsonschema/commit/7b852d451addeb63f034b93155d535c66fdbc6d7
The `fixtures/yaml_inline.json` is what I originally had when `YAMLEmbeddedStructs` was provided, but this did not seem correct as the `inline` tag is pretty explicit about intent: https://pkg.go.dev/gopkg.in/yaml.v2#Marshal . I can remove that unused fixture if this is agreeable.
=> recognize yaml inline

fixtures/custom_additional.json, reflect.go, reflect_test.go
Adds an `AdditionalFields` config that allows one to add arbitrary `StructField`s to a given type.
Why:
I've encountered a [golang project](https://github.com/prometheus/prometheus/blob/master/discovery/registry.go) which does some custom (Un)MarshallYAML for which it would be hard to capture via `TypeMapper`.
Written on #80 but not dependent (I can rebase without if necessary).
=> Additional fields

README.md, fixtures/compact_date.json, reflect.go, reflect_test.go
The aim here is to be able to support custom types without having to manually override definitions from the resulting schema. If the `JSONSchemaType() *jsonschema.Type` method is implemented in a struct, it will be used instead of the automatic struct type definition process.
Examples are provided in the README.md and tests. There is likely to be a more appropriate name for the type method, I'm open to suggestions :-)
=> Support custom type definitions

fixtures/allow_additional_props.json, fixtures/defaults.json, fixtures/defaults_expanded_toplevel.json, fixtures/fully_qualified.json, fixtures/ignore_type.json, fixtures/no_ref_qual_types.json, fixtures/no_reference.json, fixtures/required_from_jsontags.json, reflect.go, reflect_test.go
This should resolve #89.
It was a rather quick stab at trying to add the feature, so I'm happy to do any improvements/fixes you may want :)
Personally I'm not super happy with digging down into `t.Items.Enum` directly, as it leaves the door open for a panic if `t.Items` is `nil`. But as far as I can tell, by the time `t.arrayKeywords()` is called, `t.Items` will always be populated with a non-nil value.
=> feat(array): add enum support for array property types

reflect.go, reflect_test.go
This PR adds support for providing descriptions via a separate `GetFieldDocString` function. Using code generation, we can generate this `GetFieldDocString` based on the comments in the go code. (see https://github.com/amurant/helm-jsonschema-gen).
Providing descriptions via comments that are next to the struct fields is much more user-friendly than providing them via tags.
=> Add support for retrieving docs from GetFieldDocString function

.github/workflows/ci.yml, README.md
Travis is becoming increasingly restrictive for free users, so github actions can serve as a fallback here
=> Add CI using GitHub actions

fixtures/allow_additional_props.json, fixtures/defaults.json, fixtures/defaults_expanded_toplevel.json, fixtures/fully_qualified.json, fixtures/ignore_type.json, fixtures/no_ref_qual_types.json, fixtures/no_reference.json, fixtures/required_from_jsontags.json, reflect.go, reflect_test.go
RawMessage values can represent any JSON value but were previously
represented as binary data [1] in the schema. With this patch they are
represented properly [2].
[1]: `{"type": "string", "media": {"binaryEncoding": "base64"}}`
[2]: `{"additionalProperties": true}`
=> Support json.RawMessage

README.md, fixtures/custom_map_type.json, fixtures/custom_slice_type.json, fixtures/custom_type_with_interface.json, reflect.go, reflect_test.go
Not sure why this was not enabled in the first place. But it is pretty useful and decouples reflect from structs (so you do not have to use `TypeMapper`).
=> Support JSONSchemaType on any type
